# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-05 11:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Papers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Journal_Paper', models.CharField(max_length=500)),
                ('Paper_Title', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Research',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Author', models.CharField(max_length=250)),
                ('Department_name', models.CharField(max_length=500)),
                ('University_name', models.CharField(max_length=500)),
                ('Address', models.CharField(max_length=600)),
            ],
        ),
        migrations.AddField(
            model_name='papers',
            name='research',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alishapp.Research'),
        ),
    ]
