# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-05 11:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alishapp', '0002_remove_research_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='research',
            name='Address',
            field=models.CharField(default=0, max_length=600),
        ),
    ]
