# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-19 04:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserRegis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userregis',
            name='password',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
