# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-23 16:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserRegis', '0002_userregis_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='userregis',
            name='username',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
